# Generated by Django 2.2.1 on 2020-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='some', max_length=100),
            preserve_default=False,
        ),
    ]
