# Generated by Django 2.2.1 on 2020-07-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addons',
            field=models.ManyToManyField(blank=True, to='restaurants.AddOn'),
        ),
    ]
