# Generated by Django 2.2.1 on 2020-08-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200729_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
