# Generated by Django 2.2.1 on 2020-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_manifest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodspeciality',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
