# Generated by Django 2.2.1 on 2020-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_manifest', '0002_auto_20200729_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspeciality',
            name='icon',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/1599/1599774.png', max_length=250),
            preserve_default=False,
        ),
    ]
