# Generated by Django 2.2.1 on 2020-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='nutrition',
            field=models.CharField(help_text='enter in JSON', max_length=250),
        ),
    ]
