# Generated by Django 2.2.1 on 2020-07-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200729_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.CharField(default='https://i2.wp.com/www.vegrecipesofindia.com/wp-content/uploads/2013/06/matar-kulcha-recipe-1-500x500.jpg', help_text='image url from internet', max_length=250),
            preserve_default=False,
        ),
    ]
