version: "3.7"
services:
  psql:
    build:
      context: postgresql
      dockerfile: Dockerfile
      network: host
    container_name: "psql"
    restart: always
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/11/
      - postgres_logs:/var/log/postgresql/
  drf:
    build:
      context: ../
      dockerfile: docker/Dockerfile.drf
      network: host
    restart: always
    container_name: "drf"
    ports:
      - 8000:8000
    volumes:
      - ../project/:/home/ubuntu/project
    depends_on:
      - "psql"
networks:
  drf:
    driver: bridge
volumes:
  postgres_data:
  postgres_logs:
