# Generated by Django 2.2.1 on 2020-07-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('operation_manifest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(unique=True)),
                ('food_items', models.ManyToManyField(help_text='select max 5 for a day', to='restaurants.FoodItem')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation_manifest.Locality')),
            ],
            options={
                'db_table': 'mealsets',
                'unique_together': {('locality', 'delivery_date')},
            },
        ),
    ]
