# Generated by Django 2.2.1 on 2020-07-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200729_0605'),
        ('mealset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealset',
            name='food_items',
        ),
        migrations.AddField(
            model_name='mealset',
            name='food_item_five',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='mealset_food_item_five', to='restaurants.FoodItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealset',
            name='food_item_four',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='mealset_food_item_four', to='restaurants.FoodItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealset',
            name='food_item_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mealset_food_item_one', to='restaurants.FoodItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealset',
            name='food_item_three',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mealset_food_item_three', to='restaurants.FoodItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealset',
            name='food_item_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mealset_food_item_two', to='restaurants.FoodItem'),
            preserve_default=False,
        ),
    ]
